sudo: required
services:
  - docker

before_install:
  - docker build -t ronny10/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ronny10/react-test npm test -- --coverage

after_success:
  - docker build -t ronny10/multi-client ./client
  - docker build -t ronny10/multi-nginx  ./nginx
  - docker build -t ronny10/multi-server  ./server
  - docker build -t ronny10/multi-worker  ./worker
  # Log in to the docker CLI
  # Setup docker username and password as Environment variable in Travis CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to Docker Hub
  - docker push ronny10/multi-client
  - docker push ronny10/multi-nginx
  - docker push ronny10/multi-server
  - docker push ronny10/multi-worker
